# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
 
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'
 
- bash: |
   pip install pytest 
   pip install pytest-cov 
   pip install pytest-xdist 
   pip install pytest-bdd 
 
  displayName: 'Install a bunch of pip packages.'
 
 
- bash: 'pytest --junitxml=$(Build.StagingDirectory)/010.xml'
  workingDirectory:
  displayName: 'Run test'

 
 
- task: PublishTestResults@2
  displayName: 'Publish test result /010.xml'
  condition: always()
  inputs:
    failOnStandardError: 'true'
    testResultsFiles: '$(Build.StagingDirectory)/010.xml'
    testRunTitle: 010
